# Build stage
FROM node:24-alpine as build-stage

WORKDIR /app

COPY frontend/package.json /app/
RUN npm install --legacy-peer-deps

COPY frontend /app/
RUN npm run build

# Production stage
FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
