"""Initial_schema

Revision ID: 384dc12aec2e
Revises: None
Create Date: 2026-06-10 02:52:47.191948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384dc12aec2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('private_journal_password_hash', sa.String(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('assessment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tipi_q1', sa.Integer(), nullable=False),
    sa.Column('tipi_q2', sa.Integer(), nullable=False),
    sa.Column('tipi_q3', sa.Integer(), nullable=False),
    sa.Column('tipi_q4', sa.Integer(), nullable=False),
    sa.Column('tipi_q5', sa.Integer(), nullable=False),
    sa.Column('tipi_q6', sa.Integer(), nullable=False),
    sa.Column('tipi_q7', sa.Integer(), nullable=False),
    sa.Column('tipi_q8', sa.Integer(), nullable=False),
    sa.Column('tipi_q9', sa.Integer(), nullable=False),
    sa.Column('tipi_q10', sa.Integer(), nullable=False),
    sa.Column('brs_q1', sa.Integer(), nullable=False),
    sa.Column('brs_q2', sa.Integer(), nullable=False),
    sa.Column('brs_q3', sa.Integer(), nullable=False),
    sa.Column('brs_q4', sa.Integer(), nullable=False),
    sa.Column('brs_q5', sa.Integer(), nullable=False),
    sa.Column('brs_q6', sa.Integer(), nullable=False),
    sa.Column('extraversion', sa.Float(), nullable=False),
    sa.Column('agreeableness', sa.Float(), nullable=False),
    sa.Column('conscientiousness', sa.Float(), nullable=False),
    sa.Column('emotional_stability', sa.Float(), nullable=False),
    sa.Column('openness', sa.Float(), nullable=False),
    sa.Column('resilience_score', sa.Float(), nullable=False),
    sa.Column('resilience_level', sa.String(), nullable=False),
    sa.Column('initial_wellness_score', sa.Float(), nullable=True),
    sa.Column('initial_burnout_risk', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_profiles_id'), 'assessment_profiles', ['id'], unique=False)
    op.create_table('burnout_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('productivity_level', sa.Integer(), nullable=False),
    sa.Column('motivation_level', sa.Integer(), nullable=False),
    sa.Column('burnout_risk', sa.String(), nullable=False),
    sa.Column('burnout_score', sa.Float(), nullable=True),
    sa.Column('explainability', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burnout_predictions_id'), 'burnout_predictions', ['id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_table('mood_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('productivity_level', sa.Integer(), nullable=False),
    sa.Column('motivation_level', sa.Integer(), nullable=False),
    sa.Column('mood_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_logs_id'), 'mood_logs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mood_logs_id'), table_name='mood_logs')
    op.drop_table('mood_logs')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_burnout_predictions_id'), table_name='burnout_predictions')
    op.drop_table('burnout_predictions')
    op.drop_index(op.f('ix_assessment_profiles_id'), table_name='assessment_profiles')
    op.drop_table('assessment_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
